package problems;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * @author Hai
 */
public class Q2 {

	public static void main(String[] args) {
		int limit = 4000000;

		printAnswer(limit);
	}

	public static void printAnswer(int limit) {
		int prev = 1, current = 2, next = prev + current;
		int answer = 0;

		while (current < limit) {
			// fibonacci sequence
			prev = current;
			current = next;
			next = prev + current;
			
			// sum of the even-valued terms
			if (isEven(prev)) {
				answer += prev;
			}
		}
		
		System.out.println(answer);
	}

	public static boolean isEven(int number) {
		return number % 2 == 0;
	}
}
